### ISSUE TITLE
Prevent style insert

### ISSUE THREAD

**Issue by ceberocks** [zefoy/angular2-dropzone-wrapper#2]
The styles are inserted inline in the head, how can I prevent?

Thanks in advance
clemens

**Comment by sconix** [comment]
Why do you want to prevent it? If you just don't want to use the default styles I just added support for disabling them. This still loads the style files but they don't have any effect so you can use your own styles. So with 0.9.0 version there is two new inputs:

useDropzoneClass: When set to false then the default styles of dropzone library are not used.
useDzWrapperClass: When set to false then the styles of the wrapper library are not used.

**Comment by sconix** [comment]
I will close this, but if you have a good reason why you want to prevent the styles loading then I can look into that.
