### ISSUE TITLE
`dictDefaultMessage` option is not working

### ISSUE THREAD

**Issue by govorov** [zefoy/angular2-dropzone-wrapper#7]
Hi again.
I'm experiencing an issue with `dictDefaultMessage` option, component ignores it at all.
Here is a workaround (`template` binding among with `message`):
```
@Component({
  selector: 'dropzone',
  template: `
    <div *ngIf="!template && message" class="dz-default dz-message" [ngClass]="{'disabled': disabled, 'dz-placeholder': placeholder}">
      <div class="dz-text">{{message}}</div>
      <img *ngIf="placeholder" class="dz-image" [src]="placeholder">
    </div>
    <template [ngIf]="template">
      <div
        class="dz-default dz-message"
        [ngClass]="{'disabled': disabled, 'dz-placeholder': placeholder}"
        [innerHTML]="template"
      >
      </div>
    </template>
  `,
  styles: [require('./style'), require('dropzone/dist/min/dropzone.min.css')],
  encapsulation: ViewEncapsulation.None
})
export class DropzoneComponent implements OnInit, DoCheck, OnDestroy, OnChanges {

  public  dropzone     : any;
  private configDiff   : any;

  @Input() config      : DropzoneConfigInterface;
  @Input() disabled    : boolean = false;

  @Input() message     : string = 'Click or drag files to upload';
  @Input() template    : string = null;
  ...
  ...
  ...
```
But this solition looks a bit ugly. Another idea is refactor the component to a directive without any template and let Dropzone render it's default template. 

Another problem with both cases is change detection - the component must trigger it manually immidiately after all dropzone callbacks.

**Comment by sconix** [comment]
I'll look into solving this for the next release which should also has a directive for alternative usage.

**Comment by sconix** [comment]
I will release 1.1.0 tonight which brings directive usage and I also changed the component to use dictDefaultMessage if message is not provided. Hopefully these additions will fix your problems.
